### ISSUE TITLE
Python 3.9 version not available via pip or conda channel

### ISSUE THREAD

**Issue by dihm** [labscript-suite/labscript-c-extensions#2]
While this package compiled against python 3.9 successfully in the most recent action, those wheels aren't available via pip or the conda channel. This prevents installing labscript in an environment with python=3.9.

Not really sure how to fix it, mostly because I can't even figure out how to trigger a build to see what happens...

**Comment by dihm** [comment]
Apparently the ability to manually run a workflow has to be [configured](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow). Fair enough. Is it worth doing so?

Also, should we attempt to build against python 3.10 now as well?

**Comment by chrisjbillington** [comment]
It's because there hasn't been a release. All that's required to trigger an upload of new packages is to add a tag with a version number to a commit to mark is as a release, otherwise only uploads to the test PyPI and anaconda label are made.

I'll take a look, see if it's practical to build for 3.10 as well, and if so will trigger a release.

**Comment by chrisjbillington** [comment]
Arg, building anything is failing now, looks like too-long-filepaths on Windows.

Will try to workaround as was done here: do the build in a directory with a shorter filepath

https://github.com/labscript-suite/vendored-conda-builds/commit/e3ed72bf706ae309969163fc4d13cebfbde4a4ff

**Comment by chrisjbillington** [comment]
Released for 3.9

some required conda packages aren't yet available in 3.10, such as cython and conda-build, so we can't build conda packages for 3.10 yet. We could make PyPI 3.10 releases, but let's give it a month or so and see if the problem solves itself. Otherwise we can add some if statements to the workflows to skip conda packages for 3.10 but still build wheels.

**Comment by dihm** [comment]
Once again, thanks for sorting this so quickly Chris! And that is good to know about the releasing. I figured it was something simple that I was missing. 

> Arg, building anything is failing now, looks like too-long-filepaths on Windows.

Ugh. I've actually had this problem in real life once trying to install anaconda on a work laptop. Being a work laptop, there were about 50 different programs added to the system path already, so adding Anaconda with a long path put it right over the edge. It's super annoying. Glad there is a reasonable workaround. Hopefully it doesn't bit-rot like everything else.

> We could make PyPI 3.10 releases, but let's give it a month or so and see if the problem solves itself.

Agreed on waiting. I don't know too many physicists that are overly eager to keep all their packages up to date anyway. It does remind me that we should probably put what versions of python we are compatible with in the install docs somewhere. Nothing is more annoying than having to start the environment over again because conda defaulted to the newest python that isn't fully supported yet. Probably just going to copy some of the badges from the repo's readme over to the documentation landing page.
